import {
  APILAYER_KEY,
  DOMAINDUCK_API_KEY,
  IP2WHOIS_API_KEY,
  OTI_LABS_API_KEY,
  RAPIDAPI_KEY,
  RDAP_API_KEY,
  WHO_DAT_URL,
  WHOAPI_COM_KEY,
  WHOISFREAKS_KEY,
  WHOISJSON_API_KEY,
  WHOISXMLAPI_KEY,
} from './whois-env.ts';
import type { WhoisProviderConfig, WhoisProviderId } from './whois-types.ts';

export const WHOIS_PROVIDER_REGISTRY: WhoisProviderConfig[] = [
  {
    id: 'who-dat',
    label: 'who-dat',
    implemented: true,
    enabled: true,
    priority: 1,
    envKeys: ['WHO_DAT_URL', 'WHO_DAT_AUTH_KEY'],
    freeTierLabel: 'Self-hosted; depends on deployment',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: null,
    perMinuteLimit: null,
    notes: 'Primary if WHO_DAT_URL exists.',
    isConfigured: () => Boolean(WHO_DAT_URL),
  },
  {
    id: 'whoisxmlapi',
    label: 'WhoisXMLAPI',
    implemented: true,
    enabled: true,
    priority: 2,
    envKeys: ['WHOIS_API_KEY', 'VITE_WHOIS_API_KEY'],
    freeTierLabel: '500 free WHOIS queries',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: 500,
    perMinuteLimit: 10,
    notes: 'Good parsed WHOIS fallback.',
    isConfigured: () => Boolean(WHOISXMLAPI_KEY),
  },
  {
    id: 'apilayer',
    label: 'APILayer Whois API',
    implemented: true,
    enabled: true,
    priority: 3,
    envKeys: ['APILAYER_API_KEY', 'VITE_APILAYER_API_KEY'],
    freeTierLabel: '3,000 requests/month',
    supportsQuotaHeaders: true,
    monthlyFreeLimit: 3000,
    perMinuteLimit: 30,
    notes: 'Exposes monthly/daily rate-limit headers.',
    isConfigured: () => Boolean(APILAYER_KEY),
  },
  {
    id: 'whoisfreaks',
    label: 'WhoisFreaks',
    implemented: true,
    enabled: true,
    priority: 4,
    envKeys: ['WHOISFREAKS_API_KEY', 'VITE_WHOISFREAKS_API_KEY'],
    freeTierLabel: '500 signup credits',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: 500,
    perMinuteLimit: 10,
    notes: 'Live WHOIS endpoint.',
    isConfigured: () => Boolean(WHOISFREAKS_KEY),
  },
  {
    id: 'whoapi',
    label: 'WhoAPI',
    implemented: true,
    enabled: true,
    priority: 5,
    envKeys: ['WHOAPI_COM_API_KEY', 'VITE_WHOAPI_COM_API_KEY'],
    freeTierLabel: 'Verify in account',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: null,
    perMinuteLimit: 10,
    notes: 'Implemented fallback; current free quota not confirmed.',
    isConfigured: () => Boolean(WHOAPI_COM_KEY),
  },
  {
    id: 'rapidapi',
    label: 'RapidAPI Domain WHOIS Lookup',
    implemented: true,
    enabled: true,
    priority: 15,
    envKeys: ['RAPIDAPI_KEY', 'VITE_RAPIDAPI_KEY'],
    freeTierLabel: 'Marketplace plan varies',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: null,
    perMinuteLimit: 10,
    notes: 'Optional last fallback.',
    isConfigured: () => Boolean(RAPIDAPI_KEY),
  },
  {
    id: 'whoisjson',
    label: 'WhoisJSON',
    implemented: true,
    enabled: true,
    priority: 7,
    envKeys: ['WHOISJSON_API_KEY', 'VITE_WHOISJSON_API_KEY'],
    freeTierLabel: '1,000 requests/month, 20 requests/minute',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: 1000,
    perMinuteLimit: 20,
    notes: 'New backup provider. Response mapping may need adjustment after live testing.',
    isConfigured: () => Boolean(WHOISJSON_API_KEY),
  },
  {
    id: 'ip2whois',
    label: 'IP2WHOIS / IP2Location.io',
    implemented: true,
    enabled: true,
    priority: 8,
    envKeys: ['IP2WHOIS_API_KEY', 'VITE_IP2WHOIS_API_KEY'],
    freeTierLabel: '500 domain WHOIS queries/month',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: 500,
    perMinuteLimit: 10,
    notes: 'New backup provider. Response mapping may need adjustment after live testing.',
    isConfigured: () => Boolean(IP2WHOIS_API_KEY),
  },
  {
    id: 'rdap-iana',
    label: 'Direct RDAP via IANA bootstrap',
    implemented: true,
    enabled: true,
    priority: 9,
    envKeys: [],
    freeTierLabel: 'No key; registry rate limits vary',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: null,
    perMinuteLimit: 10,
    notes: 'No-key structured RDAP fallback. Uses IANA bootstrap and caches it per warm runtime.',
    isConfigured: () => true,
  },
  {
    id: 'rdap-org',
    label: 'RDAP.org bootstrap',
    implemented: true,
    enabled: true,
    priority: 10,
    envKeys: [],
    freeTierLabel: 'No key; 10 requests / 10 seconds documented',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: null,
    perMinuteLimit: 10,
    notes: 'No-key RDAP fallback. Kept after direct IANA because RDAP.org has a public Cloudflare limit.',
    isConfigured: () => true,
  },
  {
    id: 'oti-labs',
    label: 'OTI Labs WHOIS API',
    implemented: true,
    enabled: true,
    priority: 11,
    envKeys: ['OTI_LABS_API_KEY'],
    freeTierLabel: '1,000 requests/month through RapidAPI',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: 1000,
    perMinuteLimit: 10,
    notes: 'RDAP-first RapidAPI provider with port-43 fallback.',
    isConfigured: credentials => Boolean(credentials?.['oti-labs'] || OTI_LABS_API_KEY),
  },
  {
    id: 'domainduck',
    label: 'Domainduck',
    implemented: true,
    enabled: true,
    priority: 12,
    envKeys: ['DOMAINDUCK_API_KEY'],
    freeTierLabel: '2,500 requests, 500/hour with cache rules',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: 2500,
    perMinuteLimit: 8,
    notes: 'Availability and WHOIS provider. Uses WHOIS mode for expiry/name-server data.',
    isConfigured: credentials => Boolean(credentials?.domainduck || DOMAINDUCK_API_KEY),
  },
  {
    id: 'rdap-api',
    label: 'RDAP API',
    implemented: true,
    enabled: true,
    priority: 13,
    envKeys: ['RDAP_API_KEY'],
    freeTierLabel: '7-day trial, then paid plans',
    supportsQuotaHeaders: false,
    monthlyFreeLimit: null,
    perMinuteLimit: 30,
    notes: 'Commercial normalized RDAP fallback.',
    isConfigured: credentials => Boolean(credentials?.['rdap-api'] || RDAP_API_KEY),
  },
  {
    id: 'rapidapi-domains-api',
    label: 'RapidAPI Domains API',
    implemented: true,
    enabled: true,
    priority: 14,
    envKeys: ['RAPIDAPI_KEY', 'VITE_RAPIDAPI_KEY'],
    freeTierLabel: '500 requests/month through RapidAPI',
    supportsQuotaHeaders: true,
    monthlyFreeLimit: 500,
    perMinuteLimit: 6,
    notes: 'Low-priority RapidAPI backup using the Domains API WHOIS endpoint. Shares RAPIDAPI_KEY with other RapidAPI listings.',
    isConfigured: () => Boolean(RAPIDAPI_KEY),
  },
];

export const providerById = (id: WhoisProviderId) => {
  const provider = WHOIS_PROVIDER_REGISTRY.find(item => item.id === id);
  if (!provider) throw new Error(`Unknown WHOIS provider: ${id}`);
  return provider;
};
